create table tb_category
(
    color varchar(7)   not null,
    id    bigint generated by default as identity,
    name  varchar(100) not null,
    primary key (id)
);

create table tb_task
(
    done        boolean      not null,
    due_date    date,
    category_id bigint,
    created_at  timestamp(6) not null,
    id          bigint generated by default as identity,
    user_id     bigint,
    description varchar(500),
    priority    varchar(255) not null check ((priority in ('LOW', 'MEDIUM', 'HIGH'))),
    title       varchar(255) not null,
    primary key (id)
);

create table tb_user
(
    id       bigint generated by default as identity,
    name     varchar(50)  not null,
    email    varchar(255) unique,
    password varchar(255) not null,
    primary key (id)
);

alter table if exists tb_task
    add constraint FKgvf2uy07y4m78uly85eh2oxvb
    foreign key (category_id)
    references tb_category;

alter table if exists tb_task
    add constraint FKekk0jr4msqy626yiiiyrikprb
    foreign key (user_id)
    references tb_user;

