/*
====================================================
SCHEMA.SQL

Arquivo mantido apenas como referência.

Atualmente o projeto utiliza:

spring.jpa.hibernate.ddl-auto=create-drop

O Hibernate cria as tabelas automaticamente
a partir das entidades.

Caso futuramente o projeto utilize:

spring.jpa.hibernate.ddl-auto=none

ou seja migrado para um banco como PostgreSQL,
este arquivo poderá ser reutilizado para criar
o esquema manualmente.
====================================================

DROP TABLE IF EXISTS tb_task;
DROP TABLE IF EXISTS tb_category;
DROP TABLE IF EXISTS tb_user;

CREATE TABLE tb_user (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(50) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL
);

CREATE TABLE tb_category (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(100) NOT NULL,
color VARCHAR(7) NOT NULL
);

CREATE TABLE tb_task (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

title VARCHAR(255) NOT NULL,
description VARCHAR(500),
done BOOLEAN NOT NULL,

created_at DATE NOT NULL,
due_date DATE,

priority VARCHAR(20) NOT NULL,

user_id BIGINT NOT NULL,
category_id BIGINT NOT NULL,

CONSTRAINT fk_task_user
 FOREIGN KEY (user_id)
 REFERENCES tb_user(id),

CONSTRAINT fk_task_category
 FOREIGN KEY (category_id)
 REFERENCES tb_category(id)
);
*/